#! /bin/bash
### BEGIN INIT INFO
# Provides:          clockwork
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: clockwork process that fires off jobs
# Description:       clockwork process that fires off jobs
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# source rvm for the rubies
. /usr/local/lib/rvm

bin=`which clockwork`
pidpath='/var/run'
workers=1
jobfile='/var/www/zippelback/jobs/clock.rb'
user='root'
name='clockwork'

function start {
	echo -n "Starting $name: "
	for (( i=1; i<=$workers; i++ ))
	do
		start-stop-daemon --background --chuid $user --start --quiet --oknodo --make-pidfile --pidfile $pidpath/$name$i.pid --exec $bin -- $jobfile
	done
	echo "done."
}

function stop {
	echo -n "Stopping $name: "
	for (( i=1; i<=$workers; i++ ))
	do
		start-stop-daemon --stop --quiet --oknodo --pidfile $pidpath/$name$i.pid
	done
	# cleanup pids
	rm -f $pidpath/$name*
	echo "done."
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	echo -n "Restarting $name: "
	stop
	sleep 1
	start
	echo "done."
	;;
  status)
	pidcount=`ls -1 $pidpath | grep $name | wc -l`
	if [ $pidcount != '0' ]
	then
		echo "* $name is running"
	else
		echo "* $name is not running"
	fi
	;;
  *)
	echo "Usage: service $name {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0